AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Parameters:
  WebClientOrigin:
    Type: String
    Description: Web app origin
    Default: http://localhost:1234
  DyanmoDbEndpoint:
    Type: String
    Description: dynamo DB endpoint
    Default: http://host.docker.internal:8000

Description: >
  time-manager-app

  Sample SAM Template for time-manager-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowOrigin: !Join
        - ""
        - - "'"
          - !Ref WebClientOrigin
          - "'"
      AllowMethods: "'*'"
      AllowHeaders: "'*'"

Resources:
  EventsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: events
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: events
      Environment:
        Variables:
          WEB_CLIENT_ORIGIN: !Ref WebClientOrigin
          DYNAMODB_ENDPOINT: !Ref DyanmoDbEndpoint
      Events:
        GetEvents:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /events/{eventDate}
            Method: get
        PutEvents:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /events/{eventDate}/{eventId}
            Method: put
        DeleteEvents:
          Type: Api
          Properties:
            Path: /events/{eventDate}/{eventId}
            Method: delete
  TasksFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tasks
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: tasks
      Environment:
        Variables:
          WEB_CLIENT_ORIGIN: !Ref WebClientOrigin
          DYNAMODB_ENDPOINT: !Ref DyanmoDbEndpoint
      Events:
        GetTasks:
          Type: Api
          Properties:
            Path: /tasks
            Method: get
        GetHighPriorityTasks:
          Type: Api
          Properties:
            Path: /high-priority-tasks
            Method: get
        GetRemainingTasks:
          Type: Api
          Properties:
            Path: /remaining-tasks
            Method: get
        PutTasks:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: put
        GetCompletedTasksSummary:
          Type: Api
          Properties:
            Path: /completed-tasks-summary
            Method: get
