AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Parameters:
  WebClientOrigin:
    Type: String
    Description: Web app origin
    Default: http://localhost:1234
Description: >
  time-manager-app

  Sample SAM Template for time-manager-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowOrigin: !Join
        - ""
        - - "'"
          - !Ref WebClientOrigin
          - "'"
      AllowMethods: "'*'"
      AllowHeaders: "'*'"

Resources:
  EventsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: events
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          WEB_CLIENT_ORIGIN: !Ref WebClientOrigin
      Events:
        GetEvents:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /events
            Method: get
        PutEvents:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /events/{eventId}
            Method: put
  TasksFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tasks
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          WEB_CLIENT_ORIGIN: !Ref WebClientOrigin
      Events:
        GetTasks:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tasks
            Method: get
        PutTasks:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tasks/{taskId}
            Method: put
